# Generated by Django 5.2.8 on 2026-01-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_direccion_compra_fecha_compra_compra_giro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='codigo_descuento',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='notas',
        ),
    ]
