# Generated by Django 5.2.8 on 2026-02-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_activo_perfilusuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='contraseña',
            field=models.CharField(default='user123', max_length=12),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Vendedor', 'Vendedor'), ('Contador', 'Contador')], default='Vendedor', max_length=30),
        ),
    ]
