# Generated by Django 5.2.8 on 2026-02-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_apellido_perfilusuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True),
        ),
    ]
