# Generated by Django 5.2.8 on 2026-05-04 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=0, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ingreso', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('egreso', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('saldo_bancario', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('debito', 'debito'), ('capital', 'Capital')], default='interes', max_length=20)),
                ('tipo_movimiento', models.CharField(choices=[('aporte', 'Aporte'), ('retiro', 'Retiro')], default='aporte', max_length=20)),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.inversor')),
            ],
        ),
    ]
