# Generated by Django 5.2.8 on 2025-11-25 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='tipo',
            field=models.CharField(blank=True, default='Reconocimiento', max_length=30),
        ),
        migrations.AddField(
            model_name='lecturacodigo',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lecturacodigo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
