# Generated by Django 5.2.8 on 2026-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='giro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
