# Generated by Django 5.2.8 on 2026-02-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_giro_proveedor_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
    ]
