# Generated by Django 5.2.8 on 2026-05-04 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresa', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('SD', 'Sin Documento')], max_length=20, unique=True)),
                ('contador', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Folio Counters',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('SD', 'Sin Documento')], default='BOLETA', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEBITO', 'TarjetaDébito'), ('CREDITO', 'TarjetaCrédito'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEBITO', 'TarjetaDébito'), ('CREDITO', 'TarjetaCrédito'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], max_length=20)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=4)),
                ('banco_tarjeta', models.CharField(blank=True, max_length=30)),
                ('numero_operacion', models.CharField(blank=True, max_length=50)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('monto_efectivo', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('monto_tarjeta', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('monto_transferencia', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='inventario.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
    ]
