# Generated by Django 5.2.8 on 2025-11-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_activo_perfilusuario_contraseña_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='ventas/pdfs/'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura'), ('Nota de Crédito', 'Nota de Crédito'), ('Nota de Débito', 'Nota de Débito'), ('Devolución', 'Devolución'), ('Sin Documento', 'Sin Documento')], default='Boleta', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_original',
            field=models.ForeignKey(blank=True, help_text='Si esta venta es una nota de crédito/débito o devolución, referencia a la venta original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_asociadas', to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
