# Generated by Django 5.2.8 on 2026-05-04 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('SD', 'Sin Documento')], default='FACTURA', max_length=10)),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('nombre_negocio', models.CharField(blank=True, max_length=200, null=True)),
                ('rut_negocio', models.CharField(blank=True, max_length=20, null=True)),
                ('giro_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_negocio', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_compra', models.DateField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/compras/pdfs/')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEBITO', 'TarjetaDébito'), ('CREDITO', 'TarjetaCrédito'), ('CHEQUE A FECHA', 'Cheque a Fecha'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='empresa.empresa')),
                ('proveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.inventario')),
            ],
        ),
    ]
