# Generated by Django 5.2.8 on 2026-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': [('puede_ver_compras', 'Puede ver compras'), ('puede_crear_compras', 'Puede crear compras'), ('puede_editar_compras', 'Puede editar compras'), ('puede_eliminar_compras', 'Puede eliminar compras')]},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'permissions': [('puede_ver_detalles_compra', 'Puede ver detalles de compra'), ('puede_crear_detalles_compra', 'Puede crear detalles de compra'), ('puede_editar_detalles_compra', 'Puede editar detalles de compra'), ('puede_eliminar_detalles_compra', 'Puede eliminar detalles de compra')]},
        ),
    ]
