# Generated by Django 5.2.8 on 2025-11-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_add_codigo_y_notas'),
        ('compras', '0002_compra_folio_compra_iva_compra_pdf_compra_subtotal_and_more'),
    ]

    operations = [
    ]
