# Generated by Django 5.2.8 on 2026-05-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_options_alter_detallecompra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra', '-id']},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={},
        ),
    ]
