# Generated by Django 5.2.8 on 2025-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_merge_20251127_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección del proveedor', max_length=255),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Fecha del documento', null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='giro',
            field=models.CharField(blank=True, help_text='Giro del negocio', max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social del proveedor', max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del proveedor', max_length=20),
        ),
    ]
