# Generated by Django 5.2.8 on 2026-02-16 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_compra_codigo_descuento_remove_compra_fecha_and_more'),
        ('inventario', '0003_alter_producto_imagen_alter_producto_precio_compra_and_more'),
        ('proveedores', '0003_remove_proveedor_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecambiocompra',
            name='cambio',
        ),
        migrations.RemoveField(
            model_name='detallecambiocompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalledevolucioncompra',
            name='devolucion',
        ),
        migrations.RemoveField(
            model_name='detalledevolucioncompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='devolucioncompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='devolucioncompra',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra', '-id']},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='giro',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='rut',
        ),
        migrations.AddField(
            model_name='compra',
            name='ciudad_empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='ciudad_proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='comuna_empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='comuna_proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_proveedor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compra',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='compra',
            name='email_proveedor',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='giro_empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='giro_proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='razon_social_empresa',
            field=models.CharField(blank=True, help_text='Razón social de la empresa al momento de la compra', max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='razon_social_proveedor',
            field=models.CharField(blank=True, help_text='Razón social del proveedor al momento de la compra', max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='rut_empresa',
            field=models.CharField(blank=True, help_text='RUT de la empresa al momento de la compra', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='rut_proveedor',
            field=models.CharField(blank=True, help_text='RUT del proveedor al momento de la compra', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('SD', 'Sin Documento')], default='FACTURA', max_length=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.producto'),
        ),
        migrations.DeleteModel(
            name='CambioCompra',
        ),
        migrations.DeleteModel(
            name='DetalleCambioCompra',
        ),
        migrations.DeleteModel(
            name='DetalleDevolucionCompra',
        ),
        migrations.DeleteModel(
            name='DevolucionCompra',
        ),
    ]
