# Generated by Django 5.2.8 on 2025-11-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_invertido', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_inversion', models.DateTimeField(auto_now_add=True)),
                ('porcentaje_retorno', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=0, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('saldo_bancario', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('debito', 'debito'), ('capital', 'Capital')], default='interes', max_length=20)),
                ('tipo_movimiento', models.CharField(choices=[('aporte', 'Aporte'), ('retiro', 'Retiro')], default='aporte', max_length=20)),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.inversor')),
            ],
        ),
    ]
