# Generated by Django 5.2.8 on 2026-02-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_legal', models.CharField(blank=True, help_text='Nombre del representante legal', max_length=100)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social de la empresa', max_length=200)),
                ('rut', models.CharField(blank=True, help_text='RUT de la empresa', max_length=20)),
                ('giro', models.CharField(blank=True, help_text='Giro de la empresa', max_length=100)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de la empresa', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de la empresa', max_length=254)),
                ('Comuna', models.CharField(blank=True, help_text='Comuna de la empresa', max_length=100)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad de la empresa', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Región de la empresa', max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de la empresa', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logos/')),
                ('fecha_fundacion', models.DateField(blank=True, help_text='Fecha de fundación de la empresa', null=True)),
                ('numero_empleados', models.IntegerField(blank=True, help_text='Número de empleados de la empresa', null=True)),
            ],
        ),
    ]
