# Generated by Django 5.2.8 on 2025-11-25 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='contraseña',
            field=models.CharField(default='admin123', max_length=12),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 25, 1, 48, 26, 326776)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
