# Generated by Django 5.2.8 on 2026-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_view_dashboard', 'Puede ver el dashboard'), ('can_manage_users', 'Puede gestionar usuarios'), ('can_manage_products', 'Puede gestionar productos'), ('can_manage_sales', 'Puede gestionar ventas'), ('can_view_reports', 'Puede ver reportes')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
