# Generated by Django 5.2.8 on 2026-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='es_dueno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('owner', 'Dueño'), ('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado'), ('contador', 'Contador')], default='empleado', max_length=30),
        ),
    ]
