# Generated by Django 5.2.8 on 2026-05-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_es_dueno_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_view_dashboard', 'Puede ver el dashboard'), ('can_view_reports', 'Puede ver reportes'), ('can_manage_users', 'Puede gestionar usuarios'), ('can_manage_products', 'Puede gestionar productos'), ('can_manage_sales', 'Puede gestionar ventas'), ('add_users', 'Puede crear usuarios'), ('edit_users', 'Puede editar usuarios'), ('delete_users', 'Puede eliminar/desactivar usuarios'), ('add_owner', 'Puede agregar un dueño'), ('edit_owner', 'Puede editar un dueño'), ('delete_owner', 'Puede eliminar un dueño')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('owner', 'Dueño'), ('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado')], default='empleado', max_length=30),
        ),
    ]
