# Generated by Django 5.2.8 on 2025-12-01 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0002_descuento_remove_venta_usuario_venta_folio_venta_iva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descuento',
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
