# Generated by Django 5.2.8 on 2025-12-02 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_delete_descuento_alter_venta_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura'), ('Nota de Crédito', 'Nota de Crédito'), ('Nota de Débito', 'Nota de Débito'), ('Devolución', 'Devolución'), ('Sin Documento', 'Sin Documento')], max_length=20, unique=True)),
                ('contador', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Folio Counters',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('Pago Mixto', 'Pago Mixto')], max_length=30)),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, help_text='Últimos 4 dígitos', max_length=4)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('numero_operacion', models.CharField(blank=True, max_length=50)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('monto_efectivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('monto_tarjeta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('monto_transferencia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.venta')),
            ],
        ),
    ]
